<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-LDBB7HE" failures="1" tests="7" name="CartTest" time="36.592" errors="0" timestamp="2024-01-05T14:37:27 EET">
  <testcase classname="TestPackage.cartTestcases" name="checkOutTheorder" time="7.866"/>
  <testcase classname="TestPackage.cartTestcases" name="fillCheckoutDetials" time="4.662"/>
  <testcase classname="TestPackage.cartTestcases" name="removeIteamFromcart" time="6.654"/>
  <testcase classname="TestPackage.cartTestcases" name="verifyCartPageOpened" time="1.174"/>
  <testcase classname="TestPackage.cartTestcases" name="verifyContinueShoppingButton" time="1.335"/>
  <testcase classname="TestPackage.cartTestcases" name="verifyProductPriceValidDuringCheckoutProcess" time="0.955">
    <skipped/>
  </testcase> <!-- verifyProductPriceValidDuringCheckoutProcess -->
  <testcase classname="TestPackage.cartTestcases" name="verifyProductPriceValidDuringCheckoutProcess" time="0.983">
    <failure type="java.lang.AssertionError" message="expected [9.99] but found [29.99]">
      <![CDATA[java.lang.AssertionError: expected [9.99] but found [29.99]
at TestPackage.cartTestcases.verifyProductPriceValidDuringCheckoutProcess(cartTestcases.java:142)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- verifyProductPriceValidDuringCheckoutProcess -->
</testsuite> <!-- CartTest -->
